with CTE As (
    select
    
    TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
    Hour(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
    DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS DAY_OF_WEEK,
    CASE
    WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('Sat', 'Sun')
    THEN 'WEEKEND'
    ELSE 'BUSINESS DAY'
    END AS DAY_TYPE,

    CASE
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (12,1,2)
    THEN 'WINTER'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (3,4,5)
    THEN 'SPRING'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (6,7,8)
    THEN 'SUMMER'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) in (9,10,11)
    THEN 'AUTUMN'
    END AS STATION_OF_YEAR

    from {{ source('demo', 'bike') }}
    where STARTED_AT != 'started at'
)

select * from CTE